### ISSUE TITLE
ImportError no module named _curses

### ISSUE THREAD

**Issue by Pawamoy** [tonybaloney/retox#2]
When running `retox` I get this error:

```
Traceback (most recent call last):
  File "/home/pawamoy/Data/isolated/virtualenvs/py35/bin/retox", line 7, in <module>
    from retox.__main__ import main
  File "/home/pawamoy/Data/isolated/virtualenvs/py35/lib/python3.5/site-packages/retox/__main__.py", line 11, in <module>
    from asciimatics.screen import Screen
  File "/home/pawamoy/Data/isolated/virtualenvs/py35/lib/python3.5/site-packages/asciimatics/screen.py", line 1918, in <module>
    import curses
  File "/usr/local/lib/python3.5/curses/__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'
```

Am I missing a dependency here? I already have `libncurses5-dev` installed. I'm on Debian Jessie by the way.

**Comment by Pawamoy** [comment]
It might be that I built Python without support for curses back then. I'll try to rebuild it and see what happens.

**Comment by Pawamoy** [comment]
Alright, it's working now. So the solution is to install `libncurses5-dev` and rebuild Python.

**Comment by tonybaloney** [comment]
Thanks for the heads up. I’ll add it to the documentation
